name: mcp_dart
description: Dart Implementation of Model Context Protocol (MCP) SDK.
version: 1.2.0+1
repository: https://github.com/leehack/mcp_dart

resolution: workspace

environment:
  sdk: '>=3.7.0 < 4.0.0'
  flutter: '>=3.27.0'

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.24.0

false_secrets:
- /example/streamable_https/key.pem
- /example/streamable_https/cert.pem
