name: gemini_client
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  mcp_dart:
    path: ../..
  google_generative_ai: ^0.4.6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
