name: {{name}}
description: A Model Context Protocol (MCP) server.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.6.0
  logging: ^1.3.0
  mcp_dart: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
