name: mcp_dart_cli
description: CLI for Model Context Protocol (MCP) servers in Dart.
version: 0.1.5
repository: https://github.com/leehack/mcp_dart

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.4.2
  build: ^4.0.3
  mason: ^0.1.2
  path: ^1.9.1
  stream_transform: ^2.1.1
  watcher: ^1.2.0
  yaml: ^3.1.3
  mcp_dart: ^1.1.2
  mason_logger: ^0.3.3
  meta: ^1.17.0
  pub_updater: ^0.5.0

dependency_overrides:
  mcp_dart:
    path: ../../

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.24.0

executables:
  mcp_dart:
